// Generated by bun scripts/generate-rls-policy-manifest.ts. Do not edit by hand.
// biome-ignore format: preserve deterministic JSON generator output
export const EXPECTED_PUBLIC_RELATIONS = [
  {
    "policy_group": "core",
    "relation_name": "accounts",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "agent_key_quorums",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "agent_policies",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "agent_registrations",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "agent_signers",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "agent_wallets",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "agents",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "approval_queue",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "audit_archive_chunks",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "audit_archives",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "audit_chain_heads",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "audit_checkpoints",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "audit_events",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "audit_retention_policies",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "auth_kv_store",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "authenticators",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "auto_approval_rules",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "capabilities",
    "relation_name": "capabilities",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "capabilities",
    "relation_name": "capability_grants",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "capabilities",
    "relation_name": "capability_invocations",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "capabilities",
    "relation_name": "capability_rate_limit_buckets",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "condition_set_items",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "condition_sets",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "digital_asset_account_aggregations",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "digital_asset_account_wallet_lifecycles",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "digital_asset_account_wallets",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "digital_asset_accounts",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "encrypted_chain_keys",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "encrypted_keys",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "evm_wallet_nonce_inflight",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "evm_wallet_nonce_owners",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "evm_wallet_nonces",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "execution_authorization_nonces",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "global_wallet_action_confirmations",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "intents",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "operator_transfer_reservations",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "pending_proxy_requests",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "policies",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "policy_templates",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "pregenerated_wallet_claim_lifecycles",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "provider_accounts",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "provider_action_approvals",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "provider_action_audit_outbox",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "provider_action_bindings",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "provider_action_reservation_generations",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "provider_agent_budgets",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "provider_authority_tenant_state",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "provider_google_credential_lifecycles",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "provider_grants",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "provider_operations",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "provider_role_bindings",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "provider_x_credential_lifecycles",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "proxy_audit_log",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "refresh_tokens",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "registry_index",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "reputation_cache",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "secret_routes",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "secrets",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "session_signers",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "sessions",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "sponsored_gas_events",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "tenant_app_client_secrets",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "tenant_app_clients",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "tenant_configs",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "tenant_invitations",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "tenant_request_signing_keys",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "tenant_saml_assertion_replays",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "tenant_saml_authn_requests",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "tenant_saml_sso_configs",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "tenant_sso_domains",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "tenants",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "trade_sessions",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "transactions",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "upstream_credential_lease_events",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "upstream_credential_leases",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "user_push_subscriptions",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "user_tenants",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "user_wallet_app_consents",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "users",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "vault_signing_freezes",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "webhook_configs",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "webhook_deliveries",
    "relation_kind": "r",
    "partition_parents": ""
  },
  {
    "policy_group": "core",
    "relation_name": "workspaces",
    "relation_kind": "r",
    "partition_parents": ""
  }
] as const;
// biome-ignore format: preserve deterministic JSON generator output
export const EXPECTED_RLS_POLICY_DEFINITIONS = [
  {
    "policy_group": "core",
    "relation_name": "agent_key_quorums",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "agent_policies",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "(tenant_id = steward_rls.tenant_id())",
    "check_expression": "(tenant_id = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "agent_registrations",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "agent_signers",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "agent_wallets",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "(EXISTS ( SELECT 1\n   FROM agents parent\n  WHERE (((parent.id)::text = (agent_wallets.agent_id)::text) AND ((parent.tenant_id)::text = steward_rls.tenant_id()))))",
    "check_expression": "(EXISTS ( SELECT 1\n   FROM agents parent\n  WHERE (((parent.id)::text = (agent_wallets.agent_id)::text) AND ((parent.tenant_id)::text = steward_rls.tenant_id()))))"
  },
  {
    "policy_group": "core",
    "relation_name": "agents",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "approval_queue",
    "policy_name": "steward_tenant_derived",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id IS NULL) AND (EXISTS ( SELECT 1\n   FROM agents parent\n  WHERE (((parent.id)::text = (approval_queue.agent_id)::text) AND ((parent.tenant_id)::text = steward_rls.tenant_id())))))",
    "check_expression": "((tenant_id IS NULL) AND (EXISTS ( SELECT 1\n   FROM agents parent\n  WHERE (((parent.id)::text = (approval_queue.agent_id)::text) AND ((parent.tenant_id)::text = steward_rls.tenant_id())))))"
  },
  {
    "policy_group": "core",
    "relation_name": "approval_queue",
    "policy_name": "steward_tenant_direct",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "audit_archive_chunks",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "(EXISTS ( SELECT 1\n   FROM audit_archives parent\n  WHERE ((parent.id = audit_archive_chunks.archive_id) AND ((parent.tenant_id)::text = steward_rls.tenant_id()))))",
    "check_expression": "(EXISTS ( SELECT 1\n   FROM audit_archives parent\n  WHERE ((parent.id = audit_archive_chunks.archive_id) AND ((parent.tenant_id)::text = steward_rls.tenant_id()))))"
  },
  {
    "policy_group": "core",
    "relation_name": "audit_archives",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "audit_chain_heads",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "audit_checkpoints",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "audit_events",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "audit_retention_policies",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "auto_approval_rules",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "capabilities",
    "relation_name": "capabilities",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "(tenant_id = steward_rls.tenant_id())",
    "check_expression": "(tenant_id = steward_rls.tenant_id())"
  },
  {
    "policy_group": "capabilities",
    "relation_name": "capability_grants",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "(tenant_id = steward_rls.tenant_id())",
    "check_expression": "(tenant_id = steward_rls.tenant_id())"
  },
  {
    "policy_group": "capabilities",
    "relation_name": "capability_invocations",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "(tenant_id = steward_rls.tenant_id())",
    "check_expression": "(tenant_id = steward_rls.tenant_id())"
  },
  {
    "policy_group": "capabilities",
    "relation_name": "capability_rate_limit_buckets",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "(tenant_id = steward_rls.tenant_id())",
    "check_expression": "(tenant_id = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "condition_set_items",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "condition_sets",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "digital_asset_account_aggregations",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "digital_asset_account_wallet_lifecycles",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = NULLIF(current_setting('steward.tenant_id'::text, true), ''::text))",
    "check_expression": "((tenant_id)::text = NULLIF(current_setting('steward.tenant_id'::text, true), ''::text))"
  },
  {
    "policy_group": "core",
    "relation_name": "digital_asset_account_wallets",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "digital_asset_accounts",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "encrypted_chain_keys",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "(EXISTS ( SELECT 1\n   FROM agents parent\n  WHERE (((parent.id)::text = (encrypted_chain_keys.agent_id)::text) AND ((parent.tenant_id)::text = steward_rls.tenant_id()))))",
    "check_expression": "(EXISTS ( SELECT 1\n   FROM agents parent\n  WHERE (((parent.id)::text = (encrypted_chain_keys.agent_id)::text) AND ((parent.tenant_id)::text = steward_rls.tenant_id()))))"
  },
  {
    "policy_group": "core",
    "relation_name": "encrypted_keys",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "(EXISTS ( SELECT 1\n   FROM agents parent\n  WHERE (((parent.id)::text = (encrypted_keys.agent_id)::text) AND ((parent.tenant_id)::text = steward_rls.tenant_id()))))",
    "check_expression": "(EXISTS ( SELECT 1\n   FROM agents parent\n  WHERE (((parent.id)::text = (encrypted_keys.agent_id)::text) AND ((parent.tenant_id)::text = steward_rls.tenant_id()))))"
  },
  {
    "policy_group": "core",
    "relation_name": "evm_wallet_nonce_inflight",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "evm_wallet_nonce_owners",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "evm_wallet_nonces",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "execution_authorization_nonces",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "global_wallet_action_confirmations",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "intents",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "operator_transfer_reservations",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "pending_proxy_requests",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "(tenant_id = steward_rls.tenant_id())",
    "check_expression": "(tenant_id = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "policies",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "(EXISTS ( SELECT 1\n   FROM agents parent\n  WHERE (((parent.id)::text = (policies.agent_id)::text) AND ((parent.tenant_id)::text = steward_rls.tenant_id()))))",
    "check_expression": "(EXISTS ( SELECT 1\n   FROM agents parent\n  WHERE (((parent.id)::text = (policies.agent_id)::text) AND ((parent.tenant_id)::text = steward_rls.tenant_id()))))"
  },
  {
    "policy_group": "core",
    "relation_name": "policy_templates",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "pregenerated_wallet_claim_lifecycles",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "(((source_tenant_id)::text = NULLIF(current_setting('steward.tenant_id'::text, true), ''::text)) OR ((target_tenant_id)::text = NULLIF(current_setting('steward.tenant_id'::text, true), ''::text)))",
    "check_expression": "(((source_tenant_id)::text = NULLIF(current_setting('steward.tenant_id'::text, true), ''::text)) OR ((target_tenant_id)::text = NULLIF(current_setting('steward.tenant_id'::text, true), ''::text)))"
  },
  {
    "policy_group": "core",
    "relation_name": "provider_accounts",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "provider_action_approvals",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "provider_action_audit_outbox",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "provider_action_bindings",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "provider_action_reservation_generations",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "provider_agent_budgets",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "provider_authority_tenant_state",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "provider_google_credential_lifecycles",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "provider_grants",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "provider_operations",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "provider_role_bindings",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "provider_x_credential_lifecycles",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "proxy_audit_log",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "(tenant_id = steward_rls.tenant_id())",
    "check_expression": "(tenant_id = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "refresh_tokens",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "reputation_cache",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "(EXISTS ( SELECT 1\n   FROM agents parent\n  WHERE (((parent.id)::text = (reputation_cache.agent_id)::text) AND ((parent.tenant_id)::text = steward_rls.tenant_id()))))",
    "check_expression": "(EXISTS ( SELECT 1\n   FROM agents parent\n  WHERE (((parent.id)::text = (reputation_cache.agent_id)::text) AND ((parent.tenant_id)::text = steward_rls.tenant_id()))))"
  },
  {
    "policy_group": "core",
    "relation_name": "secret_routes",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "(tenant_id = steward_rls.tenant_id())",
    "check_expression": "(tenant_id = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "secrets",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "(tenant_id = steward_rls.tenant_id())",
    "check_expression": "(tenant_id = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "session_signers",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "sponsored_gas_events",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "tenant_app_client_secrets",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "tenant_app_clients",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "tenant_configs",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "tenant_invitations",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "tenant_request_signing_keys",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "tenant_saml_assertion_replays",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "tenant_saml_authn_requests",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "tenant_saml_sso_configs",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "tenant_sso_domains",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "tenants",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((id)::text = steward_rls.tenant_id())",
    "check_expression": "((id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "trade_sessions",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "transactions",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "(EXISTS ( SELECT 1\n   FROM agents parent\n  WHERE (((parent.id)::text = (transactions.agent_id)::text) AND ((parent.tenant_id)::text = steward_rls.tenant_id()))))",
    "check_expression": "(EXISTS ( SELECT 1\n   FROM agents parent\n  WHERE (((parent.id)::text = (transactions.agent_id)::text) AND ((parent.tenant_id)::text = steward_rls.tenant_id()))))"
  },
  {
    "policy_group": "core",
    "relation_name": "upstream_credential_lease_events",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "upstream_credential_leases",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "user_push_subscriptions",
    "policy_name": "steward_global_user_subscription",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id IS NULL) AND (user_id = steward_rls.user_id()))",
    "check_expression": "((tenant_id IS NULL) AND (user_id = steward_rls.user_id()))"
  },
  {
    "policy_group": "core",
    "relation_name": "user_push_subscriptions",
    "policy_name": "steward_tenant_subscription",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "user_tenants",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "user_wallet_app_consents",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "vault_signing_freezes",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "webhook_configs",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "webhook_deliveries",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "(tenant_id = steward_rls.tenant_id())",
    "check_expression": "(tenant_id = steward_rls.tenant_id())"
  },
  {
    "policy_group": "core",
    "relation_name": "workspaces",
    "policy_name": "steward_tenant_isolation",
    "command": "*",
    "permissive": true,
    "roles": "PUBLIC",
    "using_expression": "((tenant_id)::text = steward_rls.tenant_id())",
    "check_expression": "((tenant_id)::text = steward_rls.tenant_id())"
  }
] as const;
