import { spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

export type InitOptions = {
  envPath?: string;
  force?: boolean;
  runMigrations?: boolean;
  databaseUrl?: string;
  apiUrl?: string;
};

export type InitResult = {
  envPath: string;
  created: boolean;
  migrations: "ran" | "skipped";
  auditSigningKeyFormat: "hex-seed";
};

function hex(bytes: number): string {
  return randomBytes(bytes).toString("hex");
}

function platformKey(): string {
  return `stw_platform_${hex(24)}`;
}

function renderEnv(options: InitOptions): string {
  const platform = platformKey();
  const scopes = JSON.stringify({
    [platform]: ["platform:write", "platform:tenant:create"],
  });
  // Defaults target the enterprise-reference compose network (service DNS names),
  // not host loopback: the generated file is consumed by that compose profile,
  // where an explicit DATABASE_URL overrides compose's `postgres:5432` fallback
  // and the API port is not published to the host (only Caddy's 80/443 are).
  // Standalone/local users override with --database-url / --api-url.
  const databaseUrl =
    options.databaseUrl ?? "postgresql://steward:steward-change-me@postgres:5432/steward";
  return [
    "# Generated by steward init. Review before production use.",
    "# Host defaults (postgres/redis/steward.localhost) target the",
    "# enterprise-reference compose network. Override with --database-url",
    "# / --api-url for standalone or host-local runs.",
    "NODE_ENV=production",
    "PORT=3200",
    "STEWARD_API_URL=" + (options.apiUrl ?? "https://steward.localhost"),
    "DATABASE_URL=" + databaseUrl,
    "POSTGRES_DB=steward",
    "POSTGRES_USER=steward",
    "POSTGRES_PASSWORD=" + hex(24),
    "STEWARD_MASTER_PASSWORD=" + hex(32),
    "STEWARD_JWT_SECRET=" + hex(32),
    "STEWARD_SESSION_SECRET=" + hex(32),
    "STEWARD_KDF_SALT=" + hex(32),
    "STEWARD_AUDIT_HMAC_KEY=" + hex(32),
    "# Raw 32-byte Ed25519 seed hex; supported by packages/api/src/services/audit-checkpoint.ts.",
    "STEWARD_AUDIT_SIGNING_KEY=" + hex(32),
    "STEWARD_PLATFORM_KEY=" + platform,
    "STEWARD_PLATFORM_KEYS=" + platform,
    "STEWARD_PLATFORM_KEY_SCOPES='" + scopes + "'",
    "STEWARD_TENANT_ID=",
    "STEWARD_TOKEN=",
    "# Tenant API key (X-Steward-Key). Machine credential the CLI falls back to",
    "# for non-interactive agent/secret/policy/approval calls when STEWARD_TOKEN is unset.",
    "STEWARD_TENANT_KEY=",
    "RPC_URL=https://mainnet.base.org",
    "CHAIN_ID=8453",
    "REDIS_URL=redis://redis:6379",
    "STEWARD_PROXY_REQUEST_SIGNING_SECRETS=" + hex(32),
    "APP_URL=https://steward.localhost",
    "PASSKEY_RP_NAME=Steward",
    "PASSKEY_RP_ID=steward.localhost",
    "PASSKEY_ORIGIN=https://steward.localhost",
    "",
  ].join("\n");
}

function readEnvValue(source: string, key: string): string | undefined {
  for (const line of source.split(/\r?\n/)) {
    const idx = line.indexOf("=");
    if (idx <= 0) continue;
    if (line.slice(0, idx) === key) return line.slice(idx + 1).replace(/^'|'$/g, "");
  }
  return undefined;
}

export function runInit(options: InitOptions = {}): InitResult {
  const envPath = resolve(options.envPath ?? ".env");
  if (existsSync(envPath) && !options.force) {
    throw new Error(`${envPath} already exists. Re-run with --force to replace it.`);
  }

  const previous = existsSync(envPath) ? readFileSync(envPath, "utf8") : "";
  if (!previous.includes("STEWARD_AUDIT_SIGNING_KEY=") || options.force) {
    writeFileSync(envPath, renderEnv(options), { mode: 0o600 });
  }

  let migrations: InitResult["migrations"] = "skipped";
  if (options.runMigrations) {
    const envSource = readFileSync(envPath, "utf8");
    const databaseUrl = options.databaseUrl ?? readEnvValue(envSource, "DATABASE_URL");
    const result = spawnSync("bun", ["packages/db/src/migrate.ts"], {
      cwd: process.cwd(),
      env: {
        ...process.env,
        DATABASE_URL: databaseUrl ?? process.env.DATABASE_URL ?? "",
        STEWARD_ALLOW_INSECURE_DB: process.env.STEWARD_ALLOW_INSECURE_DB ?? "true",
      },
      stdio: "inherit",
    });
    if (result.status !== 0) throw new Error("Database migrations failed");
    migrations = "ran";
  }

  return { envPath, created: true, migrations, auditSigningKeyFormat: "hex-seed" };
}
