import { resolve } from "node:path";
import { migrate as pgliteMigrate } from "drizzle-orm/pglite/migrator";
import { createPGLiteDb } from "../packages/db/src/pglite";
import { runPluginMigrations } from "../packages/db/src/plugin-migrate";

const quote = (value: string | null) =>
  value === null ? "NULL" : `'${value.replaceAll("'", "''")}'`;

const { db, client } = await createPGLiteDb("memory://");
try {
  await runPluginMigrations(
    {
      id: "capabilities",
      migrationsFolder: resolve(import.meta.dir, "../packages/plugin-capabilities/drizzle"),
    },
    { db, client, useAdvisoryLock: false, migrateFn: pgliteMigrate as never },
  );
  const relations = await client.query<{
    relation_name: string;
    relation_kind: string;
    partition_parents: string;
  }>(`
    SELECT c.relname AS relation_name,
           c.relkind::text AS relation_kind,
           COALESCE(string_agg(parent.relname, ',' ORDER BY parent.relname), '') AS partition_parents
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    LEFT JOIN pg_inherits i ON i.inhrelid = c.oid
    LEFT JOIN pg_class parent ON parent.oid = i.inhparent
    LEFT JOIN pg_namespace parent_ns ON parent_ns.oid = parent.relnamespace
    WHERE n.nspname = 'public'
      AND c.relkind IN ('r', 'p')
      AND c.relname <> '__steward_migrations'
      AND (parent.oid IS NULL OR parent_ns.nspname = 'public')
    GROUP BY c.relname, c.relkind
    ORDER BY c.relname
  `);
  const policies = await client.query<{
    relation_name: string;
    policy_name: string;
    command: string;
    permissive: boolean;
    roles: string;
    using_expression: string | null;
    check_expression: string | null;
  }>(`
    SELECT c.relname AS relation_name,
           p.polname AS policy_name,
           p.polcmd::text AS command,
           p.polpermissive AS permissive,
           CASE WHEN p.polroles = ARRAY[0::oid] THEN 'PUBLIC'
                ELSE array_to_string(ARRAY(
                  SELECT r.rolname FROM pg_roles r
                  WHERE r.oid = ANY(p.polroles) ORDER BY r.rolname
                ), ',') END AS roles,
           pg_get_expr(p.polqual, p.polrelid) AS using_expression,
           pg_get_expr(p.polwithcheck, p.polrelid) AS check_expression
    FROM pg_policy p
    JOIN pg_class c ON c.oid = p.polrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND p.polname LIKE 'steward_%'
    ORDER BY c.relname, p.polname
  `);

  const output = [
    "-- Generated by bun scripts/generate-rls-policy-manifest.ts. Do not edit by hand.",
    "CREATE TEMP TABLE steward_expected_public_relations (",
    "  policy_group text NOT NULL, relation_name text PRIMARY KEY, relation_kind text NOT NULL, partition_parents text NOT NULL",
    ") ON COMMIT DROP;",
    "INSERT INTO steward_expected_public_relations VALUES",
    relations.rows
      .map(
        (row, index) =>
          `  (${quote(row.relation_name.startsWith("capabilit") ? "capabilities" : "core")},${quote(row.relation_name)},${quote(row.relation_kind)},${quote(row.partition_parents)})${
            index === relations.rows.length - 1 ? ";" : ","
          }`,
      )
      .join("\n"),
    "CREATE TEMP TABLE steward_expected_rls_policy_definitions (",
    "  policy_group text NOT NULL, relation_name text NOT NULL, policy_name text NOT NULL, command text NOT NULL,",
    "  permissive boolean NOT NULL, roles text NOT NULL, using_expression text, check_expression text,",
    "  PRIMARY KEY (relation_name, policy_name)",
    ") ON COMMIT DROP;",
    "INSERT INTO steward_expected_rls_policy_definitions VALUES",
    policies.rows
      .map(
        (row, index) =>
          `  (${quote(row.relation_name.startsWith("capabilit") ? "capabilities" : "core")},${quote(row.relation_name)},${quote(row.policy_name)},${quote(row.command)},${
            row.permissive
          },${quote(row.roles)},${quote(row.using_expression)},${quote(row.check_expression)})${
            index === policies.rows.length - 1 ? ";" : ","
          }`,
      )
      .join("\n"),
    "",
  ].join("\n");
  await Promise.all([
    Bun.write(resolve(import.meta.dir, "postgres/rls-policy-manifest.sql"), output),
    Bun.write(
      resolve(import.meta.dir, "../packages/db/src/rls-policy-manifest.generated.ts"),
      [
        "// Generated by bun scripts/generate-rls-policy-manifest.ts. Do not edit by hand.",
        "// biome-ignore format: preserve deterministic JSON generator output",
        `export const EXPECTED_PUBLIC_RELATIONS = ${JSON.stringify(
          relations.rows.map((row) => ({
            policy_group: row.relation_name.startsWith("capabilit") ? "capabilities" : "core",
            ...row,
          })),
          null,
          2,
        )} as const;`,
        "// biome-ignore format: preserve deterministic JSON generator output",
        `export const EXPECTED_RLS_POLICY_DEFINITIONS = ${JSON.stringify(
          policies.rows.map((row) => ({
            policy_group: row.relation_name.startsWith("capabilit") ? "capabilities" : "core",
            ...row,
          })),
          null,
          2,
        )} as const;`,
        "",
      ].join("\n"),
    ),
  ]);
} finally {
  await client.close();
}
