/**
 * workload-secrets.ts — the WORKLOAD-scoped secret contract (machine plane).
 *
 * Mount: app.route("/v1/workload-secrets", workloadSecretsRoutes) (behind
 * tenantAuth in app.ts; the bearer/api-key classification happens there).
 *
 * WHY THIS EXISTS (elizaos/eliza #17432): a container control plane needs to
 * seal caller-supplied env secrets into Steward and a container needs to
 * resolve them at boot — but the human `/secrets` CRUD (routes/secrets.ts) is
 * deliberately owner/admin-session + recent-MFA only and rejects machine
 * credentials, and no machine may ever hold a credential that can enumerate a
 * tenant's secret inventory. This plane is the machine path, built as two
 * DISJOINT principals with least privilege on both sides:
 *
 *   WRITER  — tenant API key (the control plane's server-side machine
 *             credential; never placed inside a workload):
 *               POST   /workloads                        register workload + P-256 key
 *                                                        (re-POST = capability rotation)
 *               PUT    /workloads/:workloadId/secrets/:name   upsert/rotate a value
 *               DELETE /workloads/:workloadId            revoke capability + secrets
 *             The writer can never READ a value back (write-only, same
 *             no-read-back property as the human plane) and there is NO list
 *             endpoint — it can only address names it already knows.
 *
 *   READER  — a short-lived agent token obtained via the PUBLIC keypair-only
 *             `/agent-enroll` challenge-response (lane A1), signed with the
 *             per-workload P-256 private key the control plane injected:
 *               POST   /resolve   { names: [...] } → { secrets, missing }
 *             The namespace is derived from the VERIFIED token's agent id
 *             (`workload/<agentId>/<name>`), so a workload can never address —
 *             or observe the existence of — another workload's or the
 *             tenant's secrets. Cross-tenant isolation is inherited from the
 *             secrets table tenant scoping.
 *
 *   HUMANS  — every session principal (owner/admin, MFA or not) is DENIED on
 *             every route: this plane cannot use a human MFA session by
 *             construction, mirroring (inverted) how the human plane rejects
 *             machine credentials.
 *
 * CAPABILITY LIFECYCLE:
 *   issue    POST /workloads registers the workload identity (an `agents` row
 *            with walletType="workload") and its P-256 signer. The keypair is
 *            generated BY THE CONTROL PLANE; the private key never crosses
 *            Steward.
 *   exercise workload enrolls (challenge/verify) → short-lived token (5m
 *            default) → /resolve. Renewal = re-enroll.
 *   rotate   re-POST /workloads with a new publicKey: previous active workload
 *            signers are revoked in the same transaction, so the old key stops
 *            enrolling immediately.
 *   revoke   DELETE /workloads/:workloadId revokes all workload signers AND
 *            soft-deletes every secret in the namespace — an outstanding
 *            (≤ TTL) token resolves nothing afterwards.
 *
 * STORAGE (extend, no forks): values are rows in the EXISTING `secrets` table
 * sealed by the EXISTING SecretVault; rotation is SecretVault's native
 * versioned rotation (the same machinery behind the human POST
 * /secrets/:id/rotate). Reads go through `exerciseSecret` (use-only closure)
 * with a FAIL-CLOSED audit `beforeUse` chokepoint — nothing new joins the
 * pinned direct-return decrypt caller set. Audit events are keys-never-values.
 */

import { importP256PublicKey } from "@stwd/auth";
import { agents as agentRows, agentSigners, getDb, type Secret, secrets } from "@stwd/db";
import { SecretVault } from "@stwd/vault";
import { and, eq, inArray, isNull, like } from "drizzle-orm";
import { type Context, Hono } from "hono";
import { type AuditEventInput, writeAuditEvent } from "../services/audit";
import {
  AGENT_SCOPE,
  type ApiResponse,
  type AppVariables,
  hasAgentTokenScope,
  MASTER_PASSWORD,
  safeJsonParse,
  setNoStoreHeaders,
} from "../services/context";

export const workloadSecretsRoutes = new Hono<{ Variables: AppVariables }>();

/** agents.id is varchar(64); keep a strict machine-id charset. */
const WORKLOAD_ID_RE = /^[A-Za-z0-9][A-Za-z0-9_.-]{0,63}$/;
/** env-var-shaped names (dots/dashes allowed for non-env consumers). */
const SECRET_NAME_RE = /^[A-Za-z0-9_][A-Za-z0-9_.-]{0,127}$/;
/** JSON delivery — multi-line values (PEM keys etc.) are legal, unlike the
 * header-injection-bound human plane. Bounded to keep rows sane. */
const MAX_SECRET_VALUE_BYTES = 64 * 1024;
/** resolve() request bound — a workload's env, not an inventory query. */
const MAX_RESOLVE_NAMES = 64;
const WORKLOAD_WALLET_TYPE = "workload";
const WORKLOAD_SIGNER_TYPE = "workload";

// Lazily initialised so context.ts can set MASTER_PASSWORD first (same pattern
// as routes/secrets.ts and routes/kms.ts — the SAME SecretVault custody plane).
let _secretVault: SecretVault | undefined;
function getSecretVault(): SecretVault {
  _secretVault ??= new SecretVault(MASTER_PASSWORD);
  return _secretVault;
}

workloadSecretsRoutes.use("*", async (c, next) => {
  setNoStoreHeaders(c);
  await next();
});

type Ctx = Context<{ Variables: AppVariables }>;

function secretNameFor(workloadId: string, name: string): string {
  return `workload/${workloadId}/${name}`;
}

// ── principals (fail-closed) ─────────────────────────────────────────────────

/**
 * WRITER gate: the tenant API key ONLY. tenantAuth already validated the key
 * hash and resolved the tenant. Session principals (any role, any MFA state),
 * agent tokens, and app secrets are all denied — this is the machine plane's
 * mirror image of the human plane's machine-credential rejection.
 */
function requireWriter(c: Ctx): { tenantId: string } | null {
  if (c.get("authType") !== "api-key") return null;
  const tenantId = c.get("tenantId");
  if (!tenantId) return null;
  return { tenantId };
}

/**
 * READER gate: a verified agent-token principal whose agent row is a WORKLOAD
 * identity. tenantAuth verified the token and confirmed the agent row exists
 * for the tenant; this gate additionally requires the standard agent scope and
 * walletType="workload" so ordinary agents and proxy-scope-only tokens stay
 * out of this plane entirely.
 */
async function requireWorkloadReader(
  c: Ctx,
): Promise<{ tenantId: string; workloadId: string } | null> {
  if (c.get("authType") !== "agent-token") return null;
  const tenantId = c.get("tenantId");
  const workloadId = c.get("agentScope");
  if (!tenantId || !workloadId) return null;
  if (!hasAgentTokenScope(c.get("agentScopes"), AGENT_SCOPE)) return null;
  const [row] = await getDb()
    .select({ walletType: agentRows.walletType })
    .from(agentRows)
    .where(and(eq(agentRows.id, workloadId), eq(agentRows.tenantId, tenantId)));
  if (!row || row.walletType !== WORKLOAD_WALLET_TYPE) return null;
  return { tenantId, workloadId };
}

function denyWriter(c: Ctx): Response {
  return c.json<ApiResponse>(
    { ok: false, error: "workload management requires the tenant API key" },
    403,
  );
}

function denyReader(c: Ctx): Response {
  return c.json<ApiResponse>(
    { ok: false, error: "resolve requires an enrolled workload token" },
    403,
  );
}

async function auditWorkload(
  c: Ctx,
  tenantId: string,
  actor: { type: "agent" | "user"; id: string },
  action: string,
  workloadId: string,
  metadata: Record<string, unknown> = {},
): Promise<void> {
  const event: AuditEventInput = {
    tenantId,
    actorType: actor.type,
    actorId: actor.id,
    action,
    resourceType: "workload",
    resourceId: workloadId,
    // keys-never-values: identifiers, names, counts, versions only.
    metadata: { workloadId, ...metadata },
    ipAddress: c.req.header("x-forwarded-for") ?? null,
    userAgent: c.req.header("user-agent") ?? null,
    requestId: c.get("requestId") ?? null,
  };
  await writeAuditEvent(event);
}

/** sha256 fingerprint of the registered public key — used as the signer
 * subjectId so (agentId, subjectType, subjectId) stays unique per key. */
async function keyFingerprint(publicKeySpkiBase64: string): Promise<string> {
  const digest = await crypto.subtle.digest(
    "SHA-256",
    new TextEncoder().encode(publicKeySpkiBase64),
  );
  return Buffer.from(digest).toString("hex").slice(0, 64);
}

// ── WRITER: POST /workloads — register / rotate a workload capability ────────

workloadSecretsRoutes.post("/workloads", async (c) => {
  const writer = requireWriter(c);
  if (!writer) return denyWriter(c);

  const body = await safeJsonParse<{
    workloadId?: unknown;
    publicKey?: unknown;
    label?: unknown;
  }>(c);
  const workloadId = typeof body?.workloadId === "string" ? body.workloadId.trim() : "";
  const publicKey = typeof body?.publicKey === "string" ? body.publicKey.trim() : "";
  const label = typeof body?.label === "string" ? body.label.trim().slice(0, 255) : null;

  if (!WORKLOAD_ID_RE.test(workloadId)) {
    return c.json<ApiResponse>({ ok: false, error: "invalid workloadId" }, 400);
  }
  // The public key must actually import as P-256 — a garbage key would brick
  // the workload's enrollment, so fail loudly at issuance time.
  if (!publicKey || !(await importP256PublicKey(publicKey))) {
    return c.json<ApiResponse>({ ok: false, error: "publicKey must be a valid P-256 key" }, 400);
  }

  const db = getDb();
  const [existing] = await db
    .select({ tenantId: agentRows.tenantId, walletType: agentRows.walletType })
    .from(agentRows)
    .where(eq(agentRows.id, workloadId));

  // agents.id is globally unique: a workloadId held by another tenant, or by a
  // NON-workload agent (never allow capability rotation to hijack a real
  // agent's signers), is a conflict — not a takeover vector.
  if (
    existing &&
    (existing.tenantId !== writer.tenantId || existing.walletType !== WORKLOAD_WALLET_TYPE)
  ) {
    return c.json<ApiResponse>({ ok: false, error: "workloadId unavailable" }, 409);
  }

  const isRotation = Boolean(existing);
  const subjectId = await keyFingerprint(publicKey);

  // Audit BEFORE the mutation (fail-closed: no capability change without its
  // audit record) — same ordering discipline as the human secrets routes.
  await auditWorkload(
    c,
    writer.tenantId,
    { type: "user", id: "api-key" },
    isRotation ? "workload.capability.rotate" : "workload.register",
    workloadId,
    { keyFingerprint: subjectId },
  );

  await db.transaction(async (tx) => {
    if (!existing) {
      await tx.insert(agentRows).values({
        id: workloadId,
        tenantId: writer.tenantId,
        name: label || workloadId,
        // Workloads hold no wallet; the column is NOT NULL so store a
        // non-address marker that can never collide with a real wallet.
        walletAddress: `workload:${workloadId}`.slice(0, 128),
        walletType: WORKLOAD_WALLET_TYPE,
      });
    }
    // Capability rotation semantics: exactly one active key per workload. All
    // previously-active workload signers die in the same transaction the new
    // one is born, so the old private key stops enrolling immediately.
    await tx
      .update(agentSigners)
      .set({ status: "revoked" })
      .where(
        and(
          eq(agentSigners.agentId, workloadId),
          eq(agentSigners.signerType, WORKLOAD_SIGNER_TYPE),
          eq(agentSigners.status, "active"),
        ),
      );
    await tx
      .insert(agentSigners)
      .values({
        tenantId: writer.tenantId,
        agentId: workloadId,
        signerType: WORKLOAD_SIGNER_TYPE,
        subjectType: WORKLOAD_SIGNER_TYPE,
        subjectId,
        keyType: "p256",
        publicKey,
        status: "active",
        label,
        createdBy: "workload-secrets:api-key",
      })
      .onConflictDoUpdate({
        target: [agentSigners.agentId, agentSigners.subjectType, agentSigners.subjectId],
        set: { status: "active", publicKey, tenantId: writer.tenantId },
      });
  });

  return c.json<ApiResponse>({
    ok: true,
    data: { workloadId, tenantId: writer.tenantId, rotated: isRotation },
  });
});

// ── WRITER: PUT /workloads/:workloadId/secrets/:name — upsert/rotate value ───

workloadSecretsRoutes.put("/workloads/:workloadId/secrets/:name", async (c) => {
  const writer = requireWriter(c);
  if (!writer) return denyWriter(c);

  const workloadId = c.req.param("workloadId");
  const name = c.req.param("name");
  if (!WORKLOAD_ID_RE.test(workloadId) || !SECRET_NAME_RE.test(name)) {
    return c.json<ApiResponse>({ ok: false, error: "invalid workloadId or secret name" }, 400);
  }

  const body = await safeJsonParse<{ value?: unknown }>(c);
  const value = typeof body?.value === "string" ? body.value : "";
  if (!value) {
    return c.json<ApiResponse>({ ok: false, error: "'value' is required" }, 400);
  }
  if (new TextEncoder().encode(value).length > MAX_SECRET_VALUE_BYTES) {
    return c.json<ApiResponse>(
      { ok: false, error: `secret value exceeds ${MAX_SECRET_VALUE_BYTES} bytes` },
      400,
    );
  }

  // The workload must exist, in THIS tenant, as a workload identity. A foreign
  // workloadId is a plain 404 (no cross-tenant existence signal).
  const [workload] = await getDb()
    .select({ tenantId: agentRows.tenantId, walletType: agentRows.walletType })
    .from(agentRows)
    .where(and(eq(agentRows.id, workloadId), eq(agentRows.tenantId, writer.tenantId)));
  if (!workload || workload.walletType !== WORKLOAD_WALLET_TYPE) {
    return c.json<ApiResponse>({ ok: false, error: "workload not found" }, 404);
  }

  const sv = getSecretVault();
  const rowName = secretNameFor(workloadId, name);
  const current = await sv.getSecret(writer.tenantId, rowName);

  await auditWorkload(
    c,
    writer.tenantId,
    { type: "user", id: "api-key" },
    current ? "workload.secret.rotate" : "workload.secret.write",
    workloadId,
    { name },
  );

  // Upsert: first write creates version 1; later writes use SecretVault's
  // native versioned rotation (the same machinery behind the human
  // POST /secrets/:id/rotate).
  const stored = current
    ? await sv.rotateSecret(writer.tenantId, rowName, value)
    : await sv.createSecret(writer.tenantId, rowName, value, {
        description: `workload secret (${workloadId})`,
      });

  // Response is metadata-only — the writer can never read a value back.
  return c.json<ApiResponse>({ ok: true, data: { name, version: stored.version } });
});

// ── WRITER: DELETE /workloads/:workloadId — revoke capability + secrets ──────

workloadSecretsRoutes.delete("/workloads/:workloadId", async (c) => {
  const writer = requireWriter(c);
  if (!writer) return denyWriter(c);

  const workloadId = c.req.param("workloadId");
  if (!WORKLOAD_ID_RE.test(workloadId)) {
    return c.json<ApiResponse>({ ok: false, error: "invalid workloadId" }, 400);
  }

  const db = getDb();
  const [workload] = await db
    .select({ walletType: agentRows.walletType })
    .from(agentRows)
    .where(and(eq(agentRows.id, workloadId), eq(agentRows.tenantId, writer.tenantId)));
  if (!workload || workload.walletType !== WORKLOAD_WALLET_TYPE) {
    return c.json<ApiResponse>({ ok: false, error: "workload not found" }, 404);
  }

  await auditWorkload(
    c,
    writer.tenantId,
    { type: "user", id: "api-key" },
    "workload.revoke",
    workloadId,
  );

  let signersRevoked = 0;
  let secretsDeleted = 0;
  await db.transaction(async (tx) => {
    // 1. Kill enrollment: every workload signer goes revoked, so no NEW token
    //    can be minted from this capability ever again.
    const revoked = await tx
      .update(agentSigners)
      .set({ status: "revoked" })
      .where(
        and(
          eq(agentSigners.agentId, workloadId),
          eq(agentSigners.signerType, WORKLOAD_SIGNER_TYPE),
          eq(agentSigners.status, "active"),
        ),
      )
      .returning({ id: agentSigners.id });
    signersRevoked = revoked.length;

    // 2. Empty the namespace: soft-delete every secret version, so an
    //    OUTSTANDING (≤ TTL) token resolves nothing for the rest of its life.
    const now = new Date();
    const deleted = await tx
      .update(secrets)
      .set({ deletedAt: now, updatedAt: now })
      .where(
        and(
          eq(secrets.tenantId, writer.tenantId),
          like(secrets.name, `workload/${workloadId}/%`),
          isNull(secrets.deletedAt),
        ),
      )
      .returning({ id: secrets.id });
    secretsDeleted = deleted.length;
  });

  return c.json<ApiResponse>({ ok: true, data: { revoked: true, signersRevoked, secretsDeleted } });
});

// ── READER: POST /resolve — a workload resolves ITS OWN values ───────────────

workloadSecretsRoutes.post("/resolve", async (c) => {
  const reader = await requireWorkloadReader(c);
  if (!reader) return denyReader(c);

  const body = await safeJsonParse<{ names?: unknown }>(c);
  const rawNames = Array.isArray(body?.names) ? body.names : null;
  if (!rawNames || rawNames.length === 0 || rawNames.length > MAX_RESOLVE_NAMES) {
    return c.json<ApiResponse>(
      { ok: false, error: `'names' must be a non-empty array of at most ${MAX_RESOLVE_NAMES}` },
      400,
    );
  }
  const names: string[] = [];
  for (const n of rawNames) {
    if (typeof n !== "string" || !SECRET_NAME_RE.test(n)) {
      return c.json<ApiResponse>({ ok: false, error: "invalid secret name in 'names'" }, 400);
    }
    if (!names.includes(n)) names.push(n);
  }

  // The namespace comes from the VERIFIED token — cross-workload/cross-tenant
  // addressing is impossible by construction (there is no field to put a
  // foreign workload id in), not by filtering.
  const db = getDb();
  const rowNames = names.map((n) => secretNameFor(reader.workloadId, n));
  const rows = await db
    .select()
    .from(secrets)
    .where(
      and(
        eq(secrets.tenantId, reader.tenantId),
        inArray(secrets.name, rowNames),
        isNull(secrets.deletedAt),
      ),
    );
  const byName = new Map<string, Secret>();
  for (const row of rows) {
    // Latest live version wins (rotation soft-deletes priors, so normally one).
    const prev = byName.get(row.name);
    if (!prev || row.version > prev.version) byName.set(row.name, row);
  }

  const sv = getSecretVault();
  const resolved: Record<string, string> = {};
  const missing: string[] = [];
  // FAIL-CLOSED audit chokepoint: the audit record is written BEFORE any
  // decryption (exerciseSecretRow beforeUse contract) — if the audit append
  // fails, no plaintext is produced. Names only, never values.
  let audited = false;
  const beforeUse = async () => {
    if (audited) return;
    await auditWorkload(
      c,
      reader.tenantId,
      { type: "agent", id: reader.workloadId },
      "workload.secrets.resolve",
      reader.workloadId,
      { names, count: names.length },
    );
    audited = true;
  };

  for (const name of names) {
    const row = byName.get(secretNameFor(reader.workloadId, name));
    if (!row) {
      missing.push(name);
      continue;
    }
    // Delivery to the workload IS the "use" — the sanctioned end of this
    // plane's plaintext path (issue #17432's boot resolution contract).
    await sv.exerciseSecretRow(
      reader.tenantId,
      row,
      (plaintext) => {
        resolved[name] = plaintext;
      },
      { beforeUse },
    );
  }

  return c.json<ApiResponse>({ ok: true, data: { secrets: resolved, missing } });
});

// ── No inventory, by construction ────────────────────────────────────────────
// There is deliberately NO `GET /workloads`, NO `GET /workloads/:id/secrets`,
// and NO way to read a value with the writer credential. Anything not defined
// above falls through to the app-level 404.
