-- Generated by bun scripts/generate-rls-policy-manifest.ts. Do not edit by hand.
CREATE TEMP TABLE steward_expected_public_relations (
  policy_group text NOT NULL, relation_name text PRIMARY KEY, relation_kind text NOT NULL, partition_parents text NOT NULL
) ON COMMIT DROP;
INSERT INTO steward_expected_public_relations VALUES
  ('core','accounts','r',''),
  ('core','agent_key_quorums','r',''),
  ('core','agent_policies','r',''),
  ('core','agent_registrations','r',''),
  ('core','agent_signers','r',''),
  ('core','agent_wallets','r',''),
  ('core','agents','r',''),
  ('core','approval_queue','r',''),
  ('core','audit_archive_chunks','r',''),
  ('core','audit_archives','r',''),
  ('core','audit_chain_heads','r',''),
  ('core','audit_checkpoints','r',''),
  ('core','audit_events','r',''),
  ('core','audit_retention_policies','r',''),
  ('core','auth_kv_store','r',''),
  ('core','authenticators','r',''),
  ('core','auto_approval_rules','r',''),
  ('capabilities','capabilities','r',''),
  ('capabilities','capability_grants','r',''),
  ('capabilities','capability_invocations','r',''),
  ('capabilities','capability_rate_limit_buckets','r',''),
  ('core','condition_set_items','r',''),
  ('core','condition_sets','r',''),
  ('core','digital_asset_account_aggregations','r',''),
  ('core','digital_asset_account_wallet_lifecycles','r',''),
  ('core','digital_asset_account_wallets','r',''),
  ('core','digital_asset_accounts','r',''),
  ('core','encrypted_chain_keys','r',''),
  ('core','encrypted_keys','r',''),
  ('core','evm_wallet_nonce_inflight','r',''),
  ('core','evm_wallet_nonce_owners','r',''),
  ('core','evm_wallet_nonces','r',''),
  ('core','execution_authorization_nonces','r',''),
  ('core','global_wallet_action_confirmations','r',''),
  ('core','intents','r',''),
  ('core','operator_transfer_reservations','r',''),
  ('core','pending_proxy_requests','r',''),
  ('core','policies','r',''),
  ('core','policy_templates','r',''),
  ('core','pregenerated_wallet_claim_lifecycles','r',''),
  ('core','provider_accounts','r',''),
  ('core','provider_action_approvals','r',''),
  ('core','provider_action_audit_outbox','r',''),
  ('core','provider_action_bindings','r',''),
  ('core','provider_action_reservation_generations','r',''),
  ('core','provider_agent_budgets','r',''),
  ('core','provider_authority_tenant_state','r',''),
  ('core','provider_google_credential_lifecycles','r',''),
  ('core','provider_grants','r',''),
  ('core','provider_operations','r',''),
  ('core','provider_role_bindings','r',''),
  ('core','provider_x_credential_lifecycles','r',''),
  ('core','proxy_audit_log','r',''),
  ('core','refresh_tokens','r',''),
  ('core','registry_index','r',''),
  ('core','reputation_cache','r',''),
  ('core','retained_user_provider_evidence','r',''),
  ('core','secret_routes','r',''),
  ('core','secrets','r',''),
  ('core','session_signers','r',''),
  ('core','sessions','r',''),
  ('core','sponsored_gas_events','r',''),
  ('core','tenant_app_client_secrets','r',''),
  ('core','tenant_app_clients','r',''),
  ('core','tenant_configs','r',''),
  ('core','tenant_invitations','r',''),
  ('core','tenant_request_signing_keys','r',''),
  ('core','tenant_saml_assertion_replays','r',''),
  ('core','tenant_saml_authn_requests','r',''),
  ('core','tenant_saml_sso_configs','r',''),
  ('core','tenant_sso_domains','r',''),
  ('core','tenants','r',''),
  ('core','trade_order_recoveries','r',''),
  ('core','trade_sessions','r',''),
  ('core','transactions','r',''),
  ('core','upstream_credential_lease_events','r',''),
  ('core','upstream_credential_leases','r',''),
  ('core','user_identity_subjects','r',''),
  ('core','user_push_subscriptions','r',''),
  ('core','user_tenants','r',''),
  ('core','user_wallet_app_consents','r',''),
  ('core','users','r',''),
  ('core','vault_signing_freezes','r',''),
  ('core','webhook_configs','r',''),
  ('core','webhook_deliveries','r',''),
  ('core','workspaces','r','');
CREATE TEMP TABLE steward_expected_rls_policy_definitions (
  policy_group text NOT NULL, relation_name text NOT NULL, policy_name text NOT NULL, command text NOT NULL,
  permissive boolean NOT NULL, roles text NOT NULL, using_expression text, check_expression text,
  PRIMARY KEY (relation_name, policy_name)
) ON COMMIT DROP;
INSERT INTO steward_expected_rls_policy_definitions VALUES
  ('core','agent_key_quorums','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','agent_policies','steward_tenant_isolation','*',true,'PUBLIC','(tenant_id = steward_rls.tenant_id())','(tenant_id = steward_rls.tenant_id())'),
  ('core','agent_registrations','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','agent_signers','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','agent_wallets','steward_tenant_isolation','*',true,'PUBLIC','(EXISTS ( SELECT 1
   FROM agents parent
  WHERE (((parent.id)::text = (agent_wallets.agent_id)::text) AND ((parent.tenant_id)::text = steward_rls.tenant_id()))))','(EXISTS ( SELECT 1
   FROM agents parent
  WHERE (((parent.id)::text = (agent_wallets.agent_id)::text) AND ((parent.tenant_id)::text = steward_rls.tenant_id()))))'),
  ('core','agents','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','approval_queue','steward_tenant_derived','*',true,'PUBLIC','((tenant_id IS NULL) AND (EXISTS ( SELECT 1
   FROM agents parent
  WHERE (((parent.id)::text = (approval_queue.agent_id)::text) AND ((parent.tenant_id)::text = steward_rls.tenant_id())))))','((tenant_id IS NULL) AND (EXISTS ( SELECT 1
   FROM agents parent
  WHERE (((parent.id)::text = (approval_queue.agent_id)::text) AND ((parent.tenant_id)::text = steward_rls.tenant_id())))))'),
  ('core','approval_queue','steward_tenant_direct','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','audit_archive_chunks','steward_tenant_isolation','*',true,'PUBLIC','(EXISTS ( SELECT 1
   FROM audit_archives parent
  WHERE ((parent.id = audit_archive_chunks.archive_id) AND ((parent.tenant_id)::text = steward_rls.tenant_id()))))','(EXISTS ( SELECT 1
   FROM audit_archives parent
  WHERE ((parent.id = audit_archive_chunks.archive_id) AND ((parent.tenant_id)::text = steward_rls.tenant_id()))))'),
  ('core','audit_archives','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','audit_chain_heads','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','audit_checkpoints','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','audit_events','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','audit_retention_policies','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','auto_approval_rules','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('capabilities','capabilities','steward_tenant_isolation','*',true,'PUBLIC','(tenant_id = steward_rls.tenant_id())','(tenant_id = steward_rls.tenant_id())'),
  ('capabilities','capability_grants','steward_tenant_isolation','*',true,'PUBLIC','(tenant_id = steward_rls.tenant_id())','(tenant_id = steward_rls.tenant_id())'),
  ('capabilities','capability_invocations','steward_tenant_isolation','*',true,'PUBLIC','(tenant_id = steward_rls.tenant_id())','(tenant_id = steward_rls.tenant_id())'),
  ('capabilities','capability_rate_limit_buckets','steward_tenant_isolation','*',true,'PUBLIC','(tenant_id = steward_rls.tenant_id())','(tenant_id = steward_rls.tenant_id())'),
  ('core','condition_set_items','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','condition_sets','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','digital_asset_account_aggregations','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','digital_asset_account_wallet_lifecycles','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = NULLIF(current_setting(''steward.tenant_id''::text, true), ''''::text))','((tenant_id)::text = NULLIF(current_setting(''steward.tenant_id''::text, true), ''''::text))'),
  ('core','digital_asset_account_wallets','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','digital_asset_accounts','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','encrypted_chain_keys','steward_tenant_isolation','*',true,'PUBLIC','(EXISTS ( SELECT 1
   FROM agents parent
  WHERE (((parent.id)::text = (encrypted_chain_keys.agent_id)::text) AND ((parent.tenant_id)::text = steward_rls.tenant_id()))))','(EXISTS ( SELECT 1
   FROM agents parent
  WHERE (((parent.id)::text = (encrypted_chain_keys.agent_id)::text) AND ((parent.tenant_id)::text = steward_rls.tenant_id()))))'),
  ('core','encrypted_keys','steward_tenant_isolation','*',true,'PUBLIC','(EXISTS ( SELECT 1
   FROM agents parent
  WHERE (((parent.id)::text = (encrypted_keys.agent_id)::text) AND ((parent.tenant_id)::text = steward_rls.tenant_id()))))','(EXISTS ( SELECT 1
   FROM agents parent
  WHERE (((parent.id)::text = (encrypted_keys.agent_id)::text) AND ((parent.tenant_id)::text = steward_rls.tenant_id()))))'),
  ('core','evm_wallet_nonce_inflight','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','evm_wallet_nonce_owners','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','evm_wallet_nonces','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','execution_authorization_nonces','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','global_wallet_action_confirmations','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','intents','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','operator_transfer_reservations','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','pending_proxy_requests','steward_tenant_isolation','*',true,'PUBLIC','(tenant_id = steward_rls.tenant_id())','(tenant_id = steward_rls.tenant_id())'),
  ('core','policies','steward_tenant_isolation','*',true,'PUBLIC','(EXISTS ( SELECT 1
   FROM agents parent
  WHERE (((parent.id)::text = (policies.agent_id)::text) AND ((parent.tenant_id)::text = steward_rls.tenant_id()))))','(EXISTS ( SELECT 1
   FROM agents parent
  WHERE (((parent.id)::text = (policies.agent_id)::text) AND ((parent.tenant_id)::text = steward_rls.tenant_id()))))'),
  ('core','policy_templates','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','pregenerated_wallet_claim_lifecycles','steward_tenant_isolation','*',true,'PUBLIC','(((source_tenant_id)::text = NULLIF(current_setting(''steward.tenant_id''::text, true), ''''::text)) OR ((target_tenant_id)::text = NULLIF(current_setting(''steward.tenant_id''::text, true), ''''::text)))','(((source_tenant_id)::text = NULLIF(current_setting(''steward.tenant_id''::text, true), ''''::text)) OR ((target_tenant_id)::text = NULLIF(current_setting(''steward.tenant_id''::text, true), ''''::text)))'),
  ('core','provider_accounts','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','provider_action_approvals','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','provider_action_audit_outbox','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','provider_action_bindings','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','provider_action_reservation_generations','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','provider_agent_budgets','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','provider_authority_tenant_state','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','provider_google_credential_lifecycles','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','provider_grants','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','provider_operations','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','provider_role_bindings','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','provider_x_credential_lifecycles','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','proxy_audit_log','steward_tenant_isolation','*',true,'PUBLIC','(tenant_id = steward_rls.tenant_id())','(tenant_id = steward_rls.tenant_id())'),
  ('core','refresh_tokens','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','reputation_cache','steward_tenant_isolation','*',true,'PUBLIC','(EXISTS ( SELECT 1
   FROM agents parent
  WHERE (((parent.id)::text = (reputation_cache.agent_id)::text) AND ((parent.tenant_id)::text = steward_rls.tenant_id()))))','(EXISTS ( SELECT 1
   FROM agents parent
  WHERE (((parent.id)::text = (reputation_cache.agent_id)::text) AND ((parent.tenant_id)::text = steward_rls.tenant_id()))))'),
  ('core','secret_routes','steward_tenant_isolation','*',true,'PUBLIC','(tenant_id = steward_rls.tenant_id())','(tenant_id = steward_rls.tenant_id())'),
  ('core','secrets','steward_tenant_isolation','*',true,'PUBLIC','(tenant_id = steward_rls.tenant_id())','(tenant_id = steward_rls.tenant_id())'),
  ('core','session_signers','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','sponsored_gas_events','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','tenant_app_client_secrets','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','tenant_app_clients','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','tenant_configs','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','tenant_invitations','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','tenant_request_signing_keys','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','tenant_saml_assertion_replays','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','tenant_saml_authn_requests','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','tenant_saml_sso_configs','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','tenant_sso_domains','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','tenants','steward_tenant_isolation','*',true,'PUBLIC','((id)::text = steward_rls.tenant_id())','((id)::text = steward_rls.tenant_id())'),
  ('core','trade_order_recoveries','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','trade_sessions','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','transactions','steward_tenant_isolation','*',true,'PUBLIC','(EXISTS ( SELECT 1
   FROM agents parent
  WHERE (((parent.id)::text = (transactions.agent_id)::text) AND ((parent.tenant_id)::text = steward_rls.tenant_id()))))','(EXISTS ( SELECT 1
   FROM agents parent
  WHERE (((parent.id)::text = (transactions.agent_id)::text) AND ((parent.tenant_id)::text = steward_rls.tenant_id()))))'),
  ('core','upstream_credential_lease_events','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','upstream_credential_leases','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','user_push_subscriptions','steward_global_user_subscription','*',true,'PUBLIC','((tenant_id IS NULL) AND (user_id = steward_rls.user_id()))','((tenant_id IS NULL) AND (user_id = steward_rls.user_id()))'),
  ('core','user_push_subscriptions','steward_tenant_subscription','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','user_tenants','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','user_wallet_app_consents','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','vault_signing_freezes','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','webhook_configs','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())'),
  ('core','webhook_deliveries','steward_tenant_isolation','*',true,'PUBLIC','(tenant_id = steward_rls.tenant_id())','(tenant_id = steward_rls.tenant_id())'),
  ('core','workspaces','steward_tenant_isolation','*',true,'PUBLIC','((tenant_id)::text = steward_rls.tenant_id())','((tenant_id)::text = steward_rls.tenant_id())');
