-- Independent, checked-in semantic ABI for the privileged RLS runtime.
-- body_md5 is md5(btrim(pg_proc.prosrc, E' \t\n\r')).
CREATE TEMP TABLE steward_expected_rls_functions (
  identity text PRIMARY KEY,
  result text NOT NULL,
  language text NOT NULL,
  volatility "char" NOT NULL,
  parallelism "char" NOT NULL,
  security_definer boolean NOT NULL,
  settings text NOT NULL,
  owner_kind text NOT NULL CHECK (owner_kind IN ('migration', 'bootstrap')),
  body_md5 text NOT NULL,
  app_execute boolean NOT NULL,
  platform_execute boolean NOT NULL
) ON COMMIT DROP;

INSERT INTO steward_expected_rls_functions VALUES
('steward_bootstrap.agent_subject(text,text,text)', 'TABLE(agent_id character varying, agent_name character varying, wallet_address character varying, signer_id uuid, signer_policy_ids jsonb, signer_expires_at timestamp with time zone, signer_revoked_at timestamp with time zone)', 'sql', 's', 'u', true, 'search_path=pg_catalog', 'bootstrap', '6125a8552be79279ff46c3ce090e7c59', true, false),
('steward_bootstrap.agent_tenant_subject(text)', 'TABLE(tenant_id character varying)', 'sql', 's', 'u', true, 'search_path=pg_catalog', 'bootstrap', '262d1aa208ccabaf62a97f92c4177050', true, false),
('steward_bootstrap.app_client_subject(text,text)', 'TABLE(secret_id uuid, secret_hash text, secret_status character varying, expires_at timestamp with time zone, revoked_at timestamp with time zone, client_enabled boolean)', 'sql', 's', 'u', true, 'search_path=pg_catalog', 'bootstrap', '58360f94b8814d8279906dc1617aadde', true, false),
('steward_bootstrap.auth_app_clients_subject(text)', 'TABLE(id character varying, allowed_redirect_urls text[], login_methods jsonb, allowed_bundle_ids text[], allowed_package_names text[])', 'sql', 's', 'u', true, 'search_path=pg_catalog', 'bootstrap', 'fb0714c071d7f6e8c7c6d9efdfd064e8', true, false),
('steward_bootstrap.auth_refresh_subject(text)', 'TABLE(user_id uuid, tenant_id character varying, expires_at timestamp with time zone)', 'sql', 's', 'u', true, 'search_path=pg_catalog', 'bootstrap', '385471ac1e27b40c1642a3b6e8acca8d', true, false),
('steward_bootstrap.auth_rotate_refresh_token(text,text,text,text,timestamp with time zone)', 'TABLE(id text, user_id uuid, tenant_id character varying, token_hash text, expires_at timestamp with time zone, created_at timestamp with time zone)', 'plpgsql', 'v', 'u', true, 'search_path=pg_catalog', 'bootstrap', '21a77b58adf302fc687f2fb2d57d7ecf', true, false),
('steward_bootstrap.auth_sso_discovery_subject(text)', 'TABLE(tenant_id character varying, domain character varying, sso_required boolean)', 'sql', 's', 'u', true, 'search_path=pg_catalog', 'bootstrap', 'ee07fe5b4f60731e95781a4e94dd82ec', true, false),
('steward_bootstrap.auth_sso_domain_subject(text,text)', 'TABLE(tenant_id character varying, sso_required boolean)', 'sql', 's', 'u', true, 'search_path=pg_catalog', 'bootstrap', '66ab0c1c1f84996bda0bc188bbdc7245', true, false),
('steward_bootstrap.auth_tenant_config_subject(text)', 'TABLE(auth_abuse_config jsonb, allowed_origins text[], email_config jsonb, oidc_providers jsonb, test_account jsonb, allowed_redirect_urls text[])', 'sql', 's', 'u', true, 'search_path=pg_catalog', 'bootstrap', '0303fafe5eb83e644f6ca645760a50bc', true, false),
('steward_bootstrap.auth_tenant_subject(text,uuid)', 'TABLE(tenant_id character varying, membership_role character varying, join_mode character varying)', 'sql', 's', 'u', true, 'search_path=pg_catalog', 'bootstrap', '943ec2ae2d1d9013f81b592b3de275ba', true, false),
('steward_bootstrap.ensure_default_membership(uuid,text)', 'void', 'plpgsql', 'v', 'u', true, 'search_path=pg_catalog', 'bootstrap', '2499470fd771b3a0eab4b9e6b0caee20', true, false),
('steward_bootstrap.ensure_default_tenant(text)', 'void', 'plpgsql', 'v', 'u', true, 'search_path=pg_catalog', 'bootstrap', 'b7b5e77547e62768088f9c003fe953d4', true, false),
('steward_bootstrap.ensure_platform_tenant()', 'text', 'sql', 'v', 'u', true, 'search_path=pg_catalog', 'bootstrap', '6ad2edf6ca56b6773d9f82f198d1afdf', true, false),
('steward_bootstrap.ensure_system_tenant()', 'text', 'sql', 'v', 'u', true, 'search_path=pg_catalog', 'bootstrap', '3777d271382a250cc2cda8a7192eecfe', true, false),
('steward_bootstrap.platform_delete_user(uuid)', 'TABLE(user_id uuid)', 'plpgsql', 'v', 'u', true, 'search_path=pg_catalog', 'bootstrap', 'e5132e59ca995fe882b92f40f321fec9', false, true),
('steward_bootstrap.platform_personal_tenant_delete(text,boolean)', 'TABLE(status text, agent_ids text[], member_ids uuid[], active_grants_retired integer, terminal_grants_removed integer, capabilities_removed integer, invocation_evidence_retained integer)', 'plpgsql', 'v', 'u', true, 'search_path=pg_catalog', 'bootstrap', 'ccc66a9c2ae899df86f528bcf61da505', false, true),
('steward_bootstrap.platform_provision_user(text,boolean,text,jsonb)', 'TABLE(user_id uuid, is_new boolean)', 'plpgsql', 'v', 'u', true, 'search_path=pg_catalog', 'bootstrap', '42cdd05b16c189c429dc47b599593f7b', false, true),
('steward_bootstrap.platform_revoke_user_refresh_tokens(uuid)', 'bigint', 'plpgsql', 'v', 'u', true, 'search_path=pg_catalog', 'bootstrap', '24c0f4afcaee667297983818f4ce5e7d', false, true),
('steward_bootstrap.platform_set_user_deactivation(uuid,boolean)', 'TABLE(user_id uuid, previous_deactivated_at timestamp with time zone, previous_updated_at timestamp with time zone, deactivated_at timestamp with time zone, tokens_revoked_before bigint)', 'plpgsql', 'v', 'u', true, 'search_path=pg_catalog', 'bootstrap', '64bd68e113e5a806bb85955b1ee1c25d', false, true),
('steward_bootstrap.platform_stats()', 'TABLE(tenant_count bigint, agent_count bigint, transaction_count bigint)', 'sql', 's', 'u', true, 'search_path=pg_catalog', 'bootstrap', '59c41666a94da8aefa942f504aaebb14', false, true),
('steward_bootstrap.platform_tenants(integer,integer)', 'TABLE(id character varying, name character varying, owner_address character varying, created_at timestamp with time zone, updated_at timestamp with time zone)', 'sql', 's', 'u', true, 'search_path=pg_catalog', 'bootstrap', '4266b6ba8a459f73e0ae396781fe71a8', false, true),
('steward_bootstrap.platform_user_identity(uuid)', 'jsonb', 'sql', 's', 'u', true, 'search_path=pg_catalog', 'bootstrap', '32738a9f1cf208e687cfb25a59e97ff7', false, true),
('steward_bootstrap.platform_user_tenant_ids(uuid)', 'TABLE(tenant_id character varying)', 'sql', 's', 'u', true, 'search_path=pg_catalog', 'bootstrap', 'c1bb79164ba144914b8a08c85c6a724f', false, true),
('steward_bootstrap.retention_delete_deactivated_users(integer)', 'bigint', 'plpgsql', 'v', 'u', true, 'search_path=pg_catalog', 'bootstrap', 'fb0bce997d27da7ac9ec5b6530f64bfa', false, true),
('steward_bootstrap.session_subject(uuid,text)', 'TABLE(deactivated_at timestamp with time zone, is_guest boolean, guest_expires_at timestamp with time zone, membership_role character varying)', 'sql', 's', 'u', true, 'search_path=pg_catalog', 'bootstrap', 'f1d5c0a5832d8113c3420e524bba8937', true, false),
('steward_bootstrap.tenant_api_key_subject(text)', 'TABLE(id character varying, name character varying, api_key_hash text, owner_address character varying, created_at timestamp with time zone, updated_at timestamp with time zone)', 'sql', 's', 'u', true, 'search_path=pg_catalog', 'bootstrap', '079dda464c16b36814995c77c761ff6b', true, false),
('steward_bootstrap.tenant_ids_for_internal_job()', 'TABLE(tenant_id character varying)', 'plpgsql', 's', 'u', true, 'search_path=pg_catalog', 'bootstrap', 'b913161e17e3a76a26f10d68226055b1', false, true),
('steward_bootstrap.tenant_set_user_deactivation(text,uuid,uuid,boolean)', 'TABLE(user_id uuid, deactivated_at timestamp with time zone, tokens_revoked_before bigint)', 'plpgsql', 'v', 'u', true, 'search_path=pg_catalog', 'bootstrap', '779adf8d604810e3639865a46ee1aa70', true, false),
('steward_bootstrap.user_token_revocation_subject(uuid)', 'bigint', 'plpgsql', 's', 'u', true, 'search_path=pg_catalog', 'bootstrap', '1015f7aa0998dea751905c61d75d6e78', true, false),
('steward_enforce_reserved_tenant_commit_state()', 'trigger', 'plpgsql', 'v', 'u', false, '', 'migration', 'd21fa9d480ee899c31a609a0599eb363', false, false),
('steward_register_user_identity_subject()', 'trigger', 'plpgsql', 'v', 'u', true, 'search_path=pg_catalog', 'migration', '88032ecac08ef35e10948b9c2e6215c9', false, false),
('steward_retire_user_identity_subject()', 'trigger', 'plpgsql', 'v', 'u', true, 'search_path=pg_catalog', 'migration', '4b23041b4549c735955ccfb9af6c30fd', false, false),
('steward_rls.tenant_id()', 'text', 'sql', 's', 's', false, 'search_path=pg_catalog', 'migration', 'a5e810ce69b3abe9d459f147d6af81ca', true, true),
('steward_rls.user_id()', 'uuid', 'sql', 's', 's', false, 'search_path=pg_catalog', 'migration', 'dfd802062414c3208389ffa762e60aea', true, false);
